# Generated by Django 5.0.6 on 2026-06-16 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('ANNOUNCEMENT', 'Announcement'), ('FEATURE', 'Feature'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.campus')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campus', '-created_at'], name='moderator_a_campus__0319d4_idx'), models.Index(fields=['status', 'campus'], name='moderator_a_status_2288de_idx')],
            },
        ),
    ]
